#!/usr/bin/env ansible-playbook

# Run script with ansible-playbook deploydev.yml
# or ./deploydev.yml

- name: Configure webserver with apache
  hosts: webservers
  sudo: True
  tasks:
  - name: install apache
    apt: name=apache update_cache=yes
  - name: copy apache config file
    copy: src=files/apachealias.conf dest=/etc/apache/conf.d/dolibarr_dev
  #- name: enable configuration
  #  file: >
  #    dest=/etc/apache/sites-enabled/default
  #    src=/etc/apache/sites-available/default
  #    state=link
  - name: copy info.html
    template: src=templates/info.html.j2 dest=/var/www/dolibarr_dev/info.html
      mode=0644
  - name: restart apache
    service: name=apache state=restarted

